name: Testing..... Production Deploy to k8s

permissions:
  id-token: write
  contents: write

env:
  ECR_REGISTRY: 560285300220.dkr.ecr.us-east-1.amazonaws.com/isr-portal

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to deploy (must start with v, e.g., v1.0.0)'
        required: true
        type: string

jobs:
  validate-release:
      name: Validate tag and check if image exists
      runs-on: arc-runners-bisnow
      steps:
        - name: validate-release
          uses: bisnow/github-actions-validate-release@v1.0
          with:
            tag: ${{ inputs.tag }}
            ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
